'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, Button, TextField, Select, Badge } from '@/components/ui';
import { ArrowLeft, Save, ClipboardList, Info, Phone, User, Home } from 'lucide-react';
import { Student, ClassLevel, TimeSlot, AdmissionStatus, StudyStatus, StudentType, StudentStatus } from '@/types';

export default function NewStudentPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  
  // Dropdown Data
  const [classLevels, setClassLevels] = useState<ClassLevel[]>([]);
  const [timeSlots, setTimeSlots] = useState<TimeSlot[]>([]);

  // Form State
  const [formData, setFormData] = useState<Partial<Student>>({
    admissionStatus: AdmissionStatus.IN_PROGRESS, // Default as per schema preference
    studyStatus: StudyStatus.REGULAR,
    status: StudentStatus.NEW,
    type: StudentType.NAZERA,
    gender: 'M',
    admissionFee: 0,
    monthlyFees: 0,
    remarks: ''
  });
  
  // Local state for dates to handle input type="date"
  const [dobInput, setDobInput] = useState('');

  useEffect(() => {
    // Fetch dropdowns
    const fetchSettings = async () => {
        const token = localStorage.getItem('accessToken');
        try {
            const [cRes, tRes] = await Promise.all([
                fetch('/api/settings/classes', { headers: { Authorization: `Bearer ${token}` } }),
                fetch('/api/settings/timeslots', { headers: { Authorization: `Bearer ${token}` } })
            ]);
            if (cRes.ok) setClassLevels(await cRes.json());
            if (tRes.ok) setTimeSlots(await tRes.json());
        } catch(e) { console.error(e); }
    };
    fetchSettings();
  }, []);

  const handleChange = (field: keyof Student, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    if (!formData.studentName || !formData.fatherName || !formData.mobile || !dobInput) {
        alert("Please fill in all required fields (Name, Father Name, Mobile, DOB)");
        setLoading(false);
        return;
    }

    try {
        const payload = {
            ...formData,
            dateOfBirth: new Date(dobInput).toISOString(),
            // Roll number is auto-generated by backend if not provided? 
            // The API generates it. We can leave it undefined.
            // But if user wants to input it? API logic: "Implement Roll Number Generation logic" is in POST. 
            // It generates it. So we don't send it unless we want to override? 
            // API doesn't seem to check if rollNumber is provided to override. It generates it ignoring input. 
            // Wait, looking at API code:
            // "const generatedRollNumber = ...; const data = { ... rollNumber: generatedRollNumber }"
            // It completely ignores input rollNumber. So we should tell user it's auto-generated.
        };

        const token = localStorage.getItem('accessToken');
        const response = await fetch('/api/students', {
            method: 'POST',
            headers: { 
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify(payload)
        });

        if (response.ok) {
            alert("Student admitted successfully!");
            router.push('/dashboard/students');
        } else {
            const err = await response.json();
            alert(`Error: ${err.error || 'Failed to create student'}`);
            if (response.status === 409) {
                alert("Duplicate record found (Form No, GR No, etc).");
            }
        }

    } catch (error) {
        console.error(error);
        alert("An unexpected error occurred.");
    } finally {
        setLoading(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-20">
      {/* Top Header */}
      <div className="flex items-center justify-between no-print">
        <div className="flex items-center gap-4">
          <Button variant="outlined" size="sm" onClick={() => router.back()} className="p-2">
            <ArrowLeft size={20} />
          </Button>
          <div>
            <h2 className="text-2xl font-bold text-gray-800 dark:text-white flex items-center gap-2">
              New Admission <span className="text-gray-400 font-normal">|</span> <span className="font-urdu text-lg">داخلہ فارم</span>
            </h2>
            <p className="text-sm text-gray-500">Fill in the student details based on the admission form.</p>
          </div>
        </div>
        <div className="flex gap-3">
          <Button variant="outlined" color="primary" onClick={() => router.back()}>Cancel</Button>
          <Button color="success" onClick={handleSubmit} isLoading={loading}>
            <Save size={18} className="mr-2" /> Save & Admit
          </Button>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-8">
        {/* Section 1: Meta Information */}
        <Card variant="neubrutal" className="border-t-4 border-primary-500">
           <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <TextField 
                label="Form No. (فارم نمبر)" 
                value={formData.formNo || ''} 
                onChange={e => handleChange('formNo', e.target.value)} 
              />
              <TextField 
                label="Gr. No. (جنرل رجسٹر نمبر)" 
                value={formData.grNumber || ''} 
                onChange={e => handleChange('grNumber', e.target.value)} 
              />
              <div className="flex flex-col justify-center">
                  <span className="text-xs text-gray-500 uppercase font-bold mb-1">Roll Number</span>
                  <span className="text-sm text-gray-400 italic">Auto-generated upon save</span>
              </div>
           </div>
        </Card>

        {/* Section 2: Student Personal Info */}
        <Card variant="neubrutal">
           <h3 className="flex items-center text-sm font-bold uppercase tracking-wider text-primary-600 mb-6 border-b pb-2">
              <User size={18} className="mr-2" /> Student's Personal Details <span className="font-urdu ml-auto text-sm text-gray-500">طالب علم کی تفصیلات</span>
           </h3>
           <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
              <TextField 
                label="Student's Full Name (طالب علم کا مکمل نام)" 
                value={formData.studentName || ''} 
                onChange={e => handleChange('studentName', e.target.value)} 
                fullWidth 
                required
              />
              <div className="grid grid-cols-2 gap-4">
                <TextField 
                    label="DOB (تاریخ پیدائش)" 
                    type="date" 
                    value={dobInput} 
                    onChange={e => setDobInput(e.target.value)} 
                    required
                />
                <TextField 
                    label="Age (عمر)" 
                    value={formData.age || ''} 
                    onChange={e => handleChange('age', parseInt(e.target.value) || undefined)}
                    type="number"
                />
              </div>
              <div className="relative mb-4">
                 <label className="block text-xs font-medium text-gray-500 mb-1">Gender (جنس)</label>
                 <Select 
                    options={[
                        { value: 'M', label: 'Male (مرد)' }, 
                        { value: 'F', label: 'Female (عورت)' }
                    ]}
                    value={formData.gender}
                    onChange={e => handleChange('gender', e.target.value)}
                 />
              </div>
           </div>
           <div className="mt-4">
              <TextField 
                label="Full Residential Address (مکمل رہائشی پتہ)" 
                value={formData.residence || ''} 
                onChange={e => handleChange('residence', e.target.value)} 
                fullWidth 
                icon={Home}
              />
               <TextField 
                label="Permanent Address (مستقل پتہ)" 
                value={formData.fullPermanentAddress || ''} 
                onChange={e => handleChange('fullPermanentAddress', e.target.value)} 
                fullWidth 
              />
           </div>
        </Card>

        {/* Section 3: Background & Contact */}
        <Card variant="neubrutal">
           <h3 className="flex items-center text-sm font-bold uppercase tracking-wider text-primary-600 mb-6 border-b pb-2">
              <Info size={18} className="mr-2" /> Academic & Family Background <span className="font-urdu ml-auto text-sm text-gray-500">پس منظر اور خاندان</span>
           </h3>
           <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
              <TextField 
                label="Father's Name (والد کا نام)" 
                value={formData.fatherName || ''} 
                onChange={e => handleChange('fatherName', e.target.value)} 
                required
              />
               <TextField 
                label="Parent/Guardian Profession (پیشہ)" 
                value={formData.parentGuardianOccupation || ''} 
                onChange={e => handleChange('parentGuardianOccupation', e.target.value)} 
              />
              <TextField 
                label="Primary Mobile (موبائل نمبر)" 
                value={formData.mobile || ''} 
                onChange={e => handleChange('mobile', e.target.value)} 
                icon={Phone}
                required
              />
              <TextField 
                label="Previous School (سابقہ اسکول)" 
                value={formData.previousSchool || ''} 
                onChange={e => handleChange('previousSchool', e.target.value)} 
              />
           </div>

           <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-8 p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg">
              <div>
                  <h4 className="text-xs font-bold text-gray-500 uppercase mb-4">Emergency Contact 1</h4>
                  <TextField 
                    label="Name" 
                    value={formData.emergencyContactName || ''} 
                    onChange={e => handleChange('emergencyContactName', e.target.value)} 
                    fullWidth
                  />
                   <TextField 
                    label="Phone" 
                    value={formData.emergencyContactPhone || ''} 
                    onChange={e => handleChange('emergencyContactPhone', e.target.value)} 
                    fullWidth
                  />
              </div>
           </div>
        </Card>

        {/* Section 4: Office Use */}
        <Card variant="neubrutal" className="bg-primary-50/50 dark:bg-primary-900/5 border border-primary-100 dark:border-primary-900/30">
           <h3 className="flex items-center text-sm font-bold uppercase tracking-wider text-primary-700 dark:text-primary-400 mb-6 border-b border-primary-200 dark:border-primary-800 pb-2">
              <ClipboardList size={18} className="mr-2" /> Office Use Only <span className="font-urdu ml-auto text-sm text-gray-500">صرف دفتری استعمال کے لئے</span>
           </h3>
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Assigned Class (درجہ)</label>
                  <Select 
                    options={[{value: '', label: 'Select Class'}, ...classLevels.map(c => ({ value: c.id, label: c.name }))]}
                    // Helper logic: we need to send classId to API, but API expects { classId, timeSlotId } or classSessionId.
                    // The API POST /students handles { classId, timeSlotId }.
                    // So we can store these in local state if we want, but formData has classSessionId? No, API POST takes classId separately.
                    onChange={e => {
                        // We are using formData loose keys for payload
                        (formData as any).classId = e.target.value;
                        setFormData({...formData});
                    }}
                  />
              </div>

              <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Time Slot (مناسب وقت)</label>
                  <Select 
                     options={[{value: '', label: 'Select Time'}, ...timeSlots.map(t => ({ value: t.id, label: `${t.label} (${t.startTime})` }))]}
                     onChange={e => {
                        (formData as any).timeSlotId = e.target.value;
                        setFormData({...formData});
                     }}
                  />
              </div>

              <div>
                  <label className="block text-xs font-medium text-gray-500 mb-1">Student Type (قسم)</label>
                  <Select 
                    options={Object.values(StudentType).map(t => ({ value: t, label: t }))}
                    value={formData.type}
                    onChange={e => handleChange('type', e.target.value)}
                  />
              </div>

              <TextField 
                label="Monthly Fees (ماہانہ فیس)" 
                type="number" 
                value={formData.monthlyFees || 0} 
                onChange={e => handleChange('monthlyFees', Number(e.target.value))} 
              />
           </div>

           <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
              <TextField 
                label="Admission Fee (ایڈمیشن فیس)" 
                type="number" 
                value={formData.admissionFee || 0} 
                onChange={e => handleChange('admissionFee', Number(e.target.value))} 
              />
              <TextField 
                label="Remark (کیفیت)" 
                value={formData.remarks || ''} 
                onChange={e => handleChange('remarks', e.target.value)} 
              />
           </div>
        </Card>

        {/* Form Actions Footer */}
        <div className="flex justify-end gap-4 pb-12">
            <Button variant="outlined" color="primary" size="lg" onClick={() => router.back()}>Discard</Button>
            <Button color="success" size="lg" type="submit" className="min-w-[200px]" isLoading={loading}>
                <Save size={18} className="mr-2" /> Complete Admission
            </Button>
        </div>
      </form>
    </div>
  );
}
